#!/bin/sh

read -p "Bouger ce bureau sur l'écran de gauche ou de droite ? (d/g) " move

if [ $move = 'd' ]
then
    i3-msg move workspace to output right > null
elif [ $move = 'g' ]
then
    i3-msg move workspace to output left > null
else
    echo "Mauvaise entrée"
fi
